# Generated by Django 3.1.3 on 2020-11-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSSICollector', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wearer',
            old_name='distance',
            new_name='X',
        ),
        migrations.AddField(
            model_name='wearer',
            name='Y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
            preserve_default=False,
        ),
    ]
